"""RED: Dashboard renders harness state, latest run, last green commit, current slice.

SPEC §'22. Operator dashboard' — a single-page HTML view that shows:
- harness version + current slice
- latest run from RunLedger (state, repository, started_at)
- last green commit hash (from slice-9 delivery ledger or stub)
- current slice number + name

The dashboard is generated by a DashboardRenderer that takes a
DashboardSnapshot frozen dataclass and returns an HTML string.

RED bullets covered:
- Renderer returns HTML string with a <h1> title.
- Snapshot is frozen; extra fields rejected.
- Empty ledger → renders "no runs" message.
- Version + slice header rendered.
- Last green commit rendered (or "unknown" if not available).
"""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

import pytest

from seharness.controller import RunLedger
from seharness.dashboard import (
    DashboardRenderer,
    DashboardSnapshot,
    GitCommit,
)


def _snapshot(**overrides) -> DashboardSnapshot:
    base = {
        "harness_version": "0.1.0",
        "current_slice": "12",
        "current_slice_name": "openclaw-packaging",
        "last_green_commit": GitCommit(
            sha="abc1234",
            message="feat: ship dashboard",
            committed_at=datetime(2026, 7, 18, tzinfo=UTC),
        ),
        "latest_run": None,
        "generated_at": datetime(2026, 7, 18, 23, 0, tzinfo=UTC),
    }
    base.update(overrides)
    return DashboardSnapshot(**base)


def test_dashboard_renderer_returns_html_string() -> None:
    renderer = DashboardRenderer()
    html = renderer.render(_snapshot())
    assert isinstance(html, str)
    assert "<html" in html.lower() or "<h1" in html.lower()


def test_dashboard_renders_version() -> None:
    renderer = DashboardRenderer()
    html = renderer.render(_snapshot(harness_version="9.9.9"))
    assert "9.9.9" in html


def test_dashboard_renders_slice() -> None:
    renderer = DashboardRenderer()
    html = renderer.render(_snapshot(current_slice="12", current_slice_name="openclaw-packaging"))
    assert "12" in html
    assert "openclaw-packaging" in html


def test_dashboard_renders_last_green_commit() -> None:
    renderer = DashboardRenderer()
    html = renderer.render(_snapshot())
    assert "abc1234" in html


def test_dashboard_renders_no_runs_message_when_empty() -> None:
    renderer = DashboardRenderer()
    html = renderer.render(_snapshot(latest_run=None))
    assert "no runs" in html.lower() or "none" in html.lower()


def test_dashboard_escapes_html_in_inputs() -> None:
    """XSS defense: snapshot fields must be escaped."""
    renderer = DashboardRenderer()
    html = renderer.render(_snapshot(current_slice_name="<script>alert(1)</script>"))
    assert "<script>alert(1)</script>" not in html
    assert "&lt;script&gt;" in html or "&lt;script" in html


def test_dashboard_snapshot_is_frozen() -> None:
    snap = _snapshot()
    with pytest.raises(Exception):  # noqa: B017
        snap.harness_version = "9.9.9"  # type: ignore[misc]


def test_dashboard_snapshot_rejects_unknown_field() -> None:
    with pytest.raises(Exception):  # noqa: B017
        DashboardSnapshot(  # type: ignore[call-arg]
            harness_version="0.1.0",
            current_slice="12",
            current_slice_name="openclaw-packaging",
            last_green_commit=None,
            latest_run=None,
            generated_at=datetime.now(tz=UTC),
            rogue_field="oops",
        )


def test_dashboard_renders_latest_run_when_present() -> None:
    ledger = RunLedger()
    ledger.record_start("run-42", repository="git@github.com:foo/bar.git")
    record = ledger.runs[0]
    renderer = DashboardRenderer()
    html = renderer.render(_snapshot(latest_run=record))
    assert "run-42" in html


def test_dashboard_write_to_file(tmp_path: Path) -> None:
    out = tmp_path / "dashboard.html"
    renderer = DashboardRenderer()
    renderer.write(_snapshot(), out)
    assert out.exists()
    content = out.read_text()
    assert "<html" in content.lower() or "<h1" in content.lower()


def test_dashboard_no_merge_buttons_rendered() -> None:
    """SPEC §'Do not merge automatically.' — dashboard MUST NOT have a
    merge button or merge link in its rendered HTML."""
    renderer = DashboardRenderer()
    html = renderer.render(_snapshot())
    lowered = html.lower()
    for forbidden in ("gh pr merge", "merge_pull_request", "auto-merge", "auto_merge"):
        assert forbidden not in lowered
    # Also no obvious merge <button>
    assert "<button" not in lowered or "merge" not in lowered
