"""WP8 (story M) — worker leases for safe multi-run execution.

The handoff doc acceptance criteria for leases:

* Two workers cannot advance the same run revision simultaneously.
* A dead worker's run becomes recoverable after lease expiry.

This module ships:

1. :class:`Lease` — frozen dataclass carrying the lease identity
   (worker_id, run_id, revision, expires_at, owner_token).
2. :class:`LeaseStore` — file-based JSONL lease log under
   ``<execution_root>/leases/``. ``acquire()`` writes a new lease
   and refuses if another live lease holds the same ``run_id``;
   ``renew()`` extends the ``expires_at``; ``release()`` removes
   the lease; ``recover_expired()`` returns the set of run_ids
   whose leases lapsed so the controller can resurrect them.
3. :class:`LeaseConflict` — raised when another worker holds the
   same run revision (or any revision of the same run).

Concurrency model:

* Single lease per ``run_id`` at any moment.
* ``acquire()`` is idempotent for the same ``owner_token`` —
   replaying an orchestrator run after a crash re-uses the same
   token, so the orchestrator does not need to recover the lease
   when it resumes.
* ``renew()`` is no-op if the lease no longer exists (e.g. it
   was explicitly released) and raises ``LeaseConflict`` if a
   different worker now owns the lease.
* ``owner_token`` is generated by the orchestrator on first
   ``start_run`` and persisted alongside the run record so a
   crashed orchestrator can resume with the same token.
"""

from __future__ import annotations

import json
import os
import secrets
import time
from collections.abc import Iterator, Mapping
from dataclasses import dataclass, field
from datetime import UTC, datetime, timedelta
from pathlib import Path


def _utcnow() -> datetime:
    return datetime.now(tz=UTC)


def _iso(value: datetime) -> str:
    return value.isoformat()


def _parse(value: str) -> datetime:
    return datetime.fromisoformat(value)


class LeaseConflict(RuntimeError):
    """Raised when another worker already holds a lease for a run."""


class LeaseNotFound(KeyError):
    """Raised when renewing or releasing a non-existent lease."""


@dataclass(frozen=True)
class Lease:
    """Immutable lease record."""

    run_id: str
    worker_id: str
    owner_token: str
    revision: int
    acquired_at: datetime
    expires_at: datetime

    def is_expired(self, now: datetime | None = None) -> bool:
        return (now or _utcnow()) >= self.expires_at

    def ttl_seconds(self, now: datetime | None = None) -> float:
        return (self.expires_at - (now or _utcnow())).total_seconds()

    def to_jsonable(self) -> Mapping[str, object]:
        return {
            "run_id": self.run_id,
            "worker_id": self.worker_id,
            "owner_token": self.owner_token,
            "revision": self.revision,
            "acquired_at": _iso(self.acquired_at),
            "expires_at": _iso(self.expires_at),
        }

    @classmethod
    def from_jsonable(cls, payload: Mapping[str, object]) -> Lease:
        return cls(
            run_id=str(payload["run_id"]),
            worker_id=str(payload["worker_id"]),
            owner_token=str(payload["owner_token"]),
            revision=int(str(payload["revision"])),
            acquired_at=_parse(str(payload["acquired_at"])),
            expires_at=_parse(str(payload["expires_at"])),
        )


def new_owner_token() -> str:
    """Generate a fresh lease owner token.

    Uses ``secrets.token_hex(16)`` so tokens are unpredictable
    across processes (defence-in-depth against lease theft by a
    misbehaving co-tenant on a shared host).
    """
    return secrets.token_hex(16)


@dataclass
class LeaseStore:
    """File-based lease log under ``<root>/leases/``."""

    root: Path
    #: Default lease duration when ``acquire()`` is called without
    #: an explicit ``ttl``. Configurable per-deployment.
    default_ttl_seconds: float = 60.0
    _leases: dict[str, Lease] = field(default_factory=dict)
    _loaded: bool = False

    def __post_init__(self) -> None:
        self.root = Path(self.root)
        self.root.mkdir(parents=True, exist_ok=True)

    # ----- Internal helpers -----

    def _path(self) -> Path:
        return self.root / "leases.jsonl"

    def _flush(self) -> None:
        path = self._path()
        tmp = path.with_suffix(".jsonl.tmp")
        with tmp.open("w", encoding="utf-8") as fh:
            for lease in self._leases.values():
                fh.write(json.dumps(lease.to_jsonable()) + "\n")
        os.replace(tmp, path)

    def _load(self) -> None:
        path = self._path()
        if not path.exists():
            self._loaded = True
            return
        with path.open("r", encoding="utf-8") as fh:
            for raw_line in fh:
                line = raw_line.strip()
                if not line:
                    continue
                lease = Lease.from_jsonable(json.loads(line))
                self._leases[lease.run_id] = lease
        self._loaded = True

    def _ensure_loaded(self) -> None:
        if not self._loaded:
            self._load()

    # ----- Lease API -----

    def get(self, run_id: str) -> Lease | None:
        self._ensure_loaded()
        return self._leases.get(run_id)

    def acquire(
        self,
        *,
        run_id: str,
        worker_id: str,
        revision: int,
        ttl_seconds: float | None = None,
        owner_token: str | None = None,
    ) -> Lease:
        """Acquire a lease for ``run_id`` at ``revision``.

        Raises :class:`LeaseConflict` if another live lease already
        holds the run. Idempotent for the same ``owner_token`` —
        replaying after a crash returns the existing lease.
        """
        self._ensure_loaded()
        now = _utcnow()
        existing = self._leases.get(run_id)
        if existing is not None:
            if existing.owner_token == owner_token:
                # Same owner: return the existing lease untouched.
                return existing
            if not existing.is_expired(now):
                raise LeaseConflict(
                    f"run {run_id!r} already leased to "
                    f"{existing.worker_id!r} (expires "
                    f"{existing.expires_at.isoformat()})"
                )
        token = owner_token or new_owner_token()
        ttl = ttl_seconds if ttl_seconds is not None else self.default_ttl_seconds
        reused_acquired_at = (
            existing.acquired_at if existing is not None and existing.owner_token == token else now
        )
        lease = Lease(
            run_id=run_id,
            worker_id=worker_id,
            owner_token=token,
            revision=revision,
            acquired_at=reused_acquired_at,
            expires_at=now + timedelta(seconds=ttl),
        )
        self._leases[run_id] = lease
        self._flush()
        return lease

    def renew(
        self,
        *,
        run_id: str,
        owner_token: str,
        ttl_seconds: float | None = None,
    ) -> Lease:
        """Renew an existing lease owned by ``owner_token``.

        Raises :class:`LeaseConflict` if a different worker now
        owns the lease, and :class:`LeaseNotFound` if the lease no
        longer exists.
        """
        self._ensure_loaded()
        existing = self._leases.get(run_id)
        if existing is None:
            raise LeaseNotFound(run_id)
        if existing.owner_token != owner_token:
            raise LeaseConflict(
                f"run {run_id!r} owned by {existing.worker_id!r}, not {owner_token[:8]!r}…"
            )
        ttl = ttl_seconds if ttl_seconds is not None else self.default_ttl_seconds
        renewed = Lease(
            run_id=existing.run_id,
            worker_id=existing.worker_id,
            owner_token=existing.owner_token,
            revision=existing.revision,
            acquired_at=existing.acquired_at,
            expires_at=_utcnow() + timedelta(seconds=ttl),
        )
        self._leases[run_id] = renewed
        self._flush()
        return renewed

    def release(self, *, run_id: str, owner_token: str) -> None:
        """Release the lease if owned by ``owner_token``.

        No-op if the lease is already gone (released by another
        worker after expiry). Raises :class:`LeaseConflict` if the
        lease is owned by a different worker.
        """
        self._ensure_loaded()
        existing = self._leases.get(run_id)
        if existing is None:
            return
        if existing.owner_token != owner_token:
            raise LeaseConflict(f"run {run_id!r} owned by {existing.worker_id!r}")
        del self._leases[run_id]
        self._flush()

    def recover_expired(self, now: datetime | None = None) -> list[str]:
        """Return the run_ids whose leases have lapsed.

        The controller calls this at startup to resurrect runs
        that were abandoned by a dead worker. The leases are
        removed from the store as a side-effect.
        """
        self._ensure_loaded()
        current = now or _utcnow()
        expired: list[str] = []
        for run_id, lease in list(self._leases.items()):
            if lease.expires_at <= current:
                expired.append(run_id)
                del self._leases[run_id]
        if expired:
            self._flush()
        return expired

    def iter_leases(self) -> Iterator[Lease]:
        self._ensure_loaded()
        return iter(tuple(self._leases.values()))


def default_lease_ttl_seconds() -> float:
    """Return the configured default lease TTL.

    Reads ``SEHARNESS_LEASE_TTL_SECONDS`` from the environment so
    deployments can tune the TTL without code changes. Default is
    60 seconds (matches the orchestrator's heartbeat cadence).
    """
    raw = os.environ.get("SEHARNESS_LEASE_TTL_SECONDS")
    if not raw:
        return 60.0
    try:
        value = float(raw)
    except ValueError as exc:
        raise ValueError(f"SEHARNESS_LEASE_TTL_SECONDS must be a float, got {raw!r}") from exc
    if value <= 0:
        raise ValueError(f"SEHARNESS_LEASE_TTL_SECONDS must be > 0, got {value}")
    return value


__all__ = [
    "Lease",
    "LeaseConflict",
    "LeaseNotFound",
    "LeaseStore",
    "default_lease_ttl_seconds",
    "new_owner_token",
]


# Sentinel used in some hot paths; ensure ``time`` is reachable
# for callers that want to compare monotonic timestamps.
_ = (time,)
